### ISSUE TITLE
nil Value

### ISSUE THREAD

**Issue by UrbanSide** [cadergator10/opencomputer-security-system#13]
![2022-06-10_13 51 54](https://user-images.githubusercontent.com/26259129/173051708-0f433e89-47b2-4626-87ee-0ba9c6d96f3f.png)

**Comment by UrbanSide** [comment]
![2022-06-10_14 01 27](https://user-images.githubusercontent.com/26259129/173052249-02f879b8-2cf5-4832-bd73-71c84342b95b.png)

**Comment by cadergator10** [comment]
First thing I can think of is did you write the card correctly? The first image is usually called by a card without any data on it as there is no array on it. One more thing: is this your first time using the system or did you update the server from an older version? I'm going to try and replicate the issue quickly, but it would help a lot if you could let me know what you did to get to this point

**Comment by cadergator10** [comment]
Spent a bit of time resetting up the system and trying to break it, and I can't think of how this could have happened. Only thing I can think of is you upgraded to a newer version which required resetting up passes, but it doesnt seem like that. I'm unable to get any further to fixing this without any info on how you got to this point.

**Comment by UrbanSide** [comment]
hmm, well, I did it like this: I installed MineOS in it, installed a program for working with maps, then I assembled a second computer, installed OpenOS on it, downloaded server raw 2 versions and also installed OpenOS on the third computer and launched the controller installation with an autoinstaller with pastebin.  

P.S I write through a translator, it may not be clear.

**Comment by UrbanSide** [comment]
and by the way, after creating the first map, userlist.txt is filled with one word nil

**Comment by cadergator10** [comment]
Try performing del userlist.txt on the server, then start server and close it. Then tell me if it still has nil.
I think it might be an issue with the database. Are you using the 2.0 database? (Version should be on the database and should read 2.3.0)
I'll be able to help more later

**Comment by UrbanSide** [comment]
I have this on my hard drive where MineOS is installed
`{{date="16/12/72 11:13:55",link="nil",uuid="a9241502-232e-4197-9e4e-c385e93bab45",level=5,staff=false,name="Aralim",blocked=false},{date="16/12/72 13:23:45",link="nil",uuid="5a06747d-afd4-4fb5-86c5-e8d8e997debb",level=3,staff=false,name="Test",blocked=false},settings={calls={"checkLevel"},above={true},label={"Level"},type={"int"},data={false},var={"level"}}}`
Its i have in the hard drive server
`{settings={label={"Level"},type={"int"},var={"level"},data={false},calls={"checkLevel"},above={true}}}`

I write step by step:

1. Installed MineOS
2. Installed Database from the "app market"
3. Installed https://github.com/cadergator10/opencomputer-security-system/blob/main/src/server/2.%23.%23/server.lua on the second computer, launched.
4. `{settings={var={"level"},label={"Level"},type={"int"},calls={"checkLevel"},data={false},above={true}}}` Such a file(**userlist.txt**) was created next to the **server.lua** file
5. Burning a new card in MineOS
6. The file userlist.txt in the folder next to **server.lua** becomes **nil**

_Because of this, it is not possible to work with the doors in the future._

**P.S** And the question arose, why don't we take the file directly from the MineOS computer to avoid the server? Or is this not realistic?

**Comment by UrbanSide** [comment]
I figured it out. It turns out that in MineOS the crypto key itself has changed from the default one. And I left the standard one everywhere in other places.
If you want, I can translate / write a guide for this system in Russian, because it is quite popular, but there are few answers to questions, so I wrote to you)

**Comment by UrbanSide** [comment]
**And one more question, is it possible to make an inverted signal in the primary door settings? For some door mods, this is unfortunately necessary.**

**Comment by cadergator10** [comment]
> I figured it out. It turns out that in MineOS the crypto key itself has changed from the default one. And I left the standard one everywhere in other places.

Sweet! I'm glad you figured that out. Odd that I couldn't replicate that issue when I tried changing the cryptkey, but good that it works now.

> If you want, I can translate / write a guide for this system in Russian, because it is quite popular, but there are few answers to questions, so I wrote to you)

That would be awesome! I can probably add the language files in update 2.4.0

> **And one more question, is it possible to make an inverted signal in the primary door settings? For some door mods, this is unfortunately necessary.**

The only way you could invert the signal is with a redstone torch atm (or with a not gate in project red.)

**Comment by UrbanSide** [comment]
Well, I was able to invert the signal through the replacement here
```
        if(component.redstone.getOutput(redSideH) == 0) then
            component.redstone.setOutput(redSideH,0)
        else
            component.redstone.setOutput(redSideH,15)
        end
```
But this is a crutch, I agree. Later I will do it right.

> That would be awesome! I can probably add the language files in update 2.4.0

I will wait for the update and I can help as soon as it is needed)
And as I understand it, multiple doors cannot yet work with a redstone signal? Only a door controller?

**Comment by cadergator10** [comment]
> Well, I was able to invert the signal through the replacement here
> ```
>         if(component.redstone.getOutput(redSideH) == 0) then
>             component.redstone.setOutput(redSideH,0)
>         else
>             component.redstone.setOutput(redSideH,15)
>         end
> ```

By the looks of it, that change to the code will cause the redstone to never change, as if the signal is 0 (no redstone) then it sets it to 0. I don't think it will ever change, but I'll have to double check and make sure.

> And as I understand it, multiple doors cannot yet work with a redstone signal? Only a door controller?

If you have bundled redstone (through the use of the Project Red mod) then you can connect bundled redstone to the back of the computer and use that with the multidoor. Otherwise yeah, no redstone will work with the multidoor.

**Comment by cadergator10** [comment]
@UrbanSide Here is the lang file for the next update https://github.com/cadergator10/opencomputer-security-system/blob/remotecontrol/src/database/MineOS/2.%23.%23/Localizations/English.lang

**Comment by cadergator10** [comment]
@UrbanSide Here is the lang file for the next update https://github.com/cadergator10/opencomputer-security-system/blob/remotecontrol/src/database/MineOS/2.%23.%23/Localizations/English.lang

**Comment by UrbanSide** [comment]
> @UrbanSide Here is the lang file for the next update https://github.com/cadergator10/opencomputer-security-system/blob/remotecontrol/src/database/MineOS/2.%23.%23/Localizations/English.lang


Here, then it will be necessary to look in the game and can correct the "logicality" on the spot
```
{
    name = "База данных",

    cardwriteralert = "Требуется подключенный модуль записи карт Open Security",
    modemalert = "Требуется модем",
    buttoncallbackalert = "ошибка в обратном вызове кнопки с идентификатором: ",
    addvaralert = "Произошла ошибка в функции addVarYesCall. Пожалуйста, сообщите об этом автору.",
    cryptalert = "Рекомендуется проверить настройки cryptKey в файле dbsettings.txt в каталоге приложения. В настоящее время по умолчанию {1,2,3,4,5}. Если сервер настроен на другой cryptKey, он не будет работать и это приведет к сбою сервера.",
    userlistfailgrab = "Не удалось получить список пользователей. Сервер онлайн? Откат к сохраненному списку пользователей",

    cardpresent = "Карта найдена",
    cardabsent = "Карта не найдена",
    linkinstruction = "У вас есть 20 секунд, чтобы связать свое устройство. Ничего не нажимай",
    linksuccess = "Связывание успешно",
    linkfail = "Связывание не удалось",

    changeuuidline1 = "Это приведет к сбросу uuid этого пользователя, что сделает все карты, связанные с ним, бесполезными.",
    changeuuidline2 = "Используйте это, если карта украдена или в другой чрезвычайной ситуации.",
    changeuuidline3 = "Вы уверены что хотите продолжить?",

    yes = "Да",
    no = "Нет",

    cardlabel = "пропуск безопасности",
    diagcardlabel = "ДИАГНОСТИЧЕСКАЯ КАРТА АДМИНИСТРАТОРА",

    newvarcheckabove = "проверьте значение выше",
    newvargroup = "группы (запятая разделяет каждую группу)",
    newvaradded = "Добавлена новая переменная. Приложение будет автоматически закрыто, и изменения будут применены при следующем запуске.",
    newvarkey = "Ключ переменной",
    newvarlabel = "Название переменной",
    newvaraddbutton = "Добавить переменную в систему",
    delvarcompleted = Переменная удалена. Приложение будет автоматически закрыто, и изменения будут применены при следующем запуске.",
    delvarcompletedbutton = "удалить переменную из системы",
    changevarpropbutton = "изменить свойства переменных",

    usernotselected = "Пользователь не выбран",
    toggle = "Переключить",
    inputname = "Ввод имени",
    inputtext = "Ввод текста"
    linkdevice = "Связанное устройство"
    new = "Новый",
    delete = "Удалить",
    resetuuid = "Сбросить uuid",
    admincardbutton = "Дебаг админ карта",
    addvar = "Добавить переменную",
    delvar = "Удалить переменную",
    editvar = "Изменить переменную",
    writebutton = "Записать",
    updateserver = "Обновить сервер"
}
```

**Comment by cadergator10** [comment]
@UrbanSide I updated the system to update 2.3.1, which includes the lang files.
