### ISSUE TITLE
can't use more than 10 sectors

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#25]
**Describe the bug**
i can't use more than 10 sectors
you can't edit the ones past 10

**To Reproduce**
1.create more than 10 sectors

**Expected behavior**
being able to click the plus to change page or something?

**Mod versions:**
 -Open Computers version: OpenComputers-MC1.12.2-1.7.7+5413028.jar
 -Open Security version: OpenSecurity-1.12.2-1.0-93.jar

**Comment by cadergator10** [comment]
Thank you for the feedback! I found the issue and it should be fixed (as well as across all the modules, as every module had this issue) Reinstalling all your modules should fix everything

However, this brought up a bug in the sectorcontrol program where having more than that wouldn't show up or cause it to crash (with over 10 sectors), so I'm working on that now before closing

**Comment by cadergator10** [comment]
Fixed the sectorcontrol program. All should be working now :)

**Comment by enderman-2009** [comment]
thanks
