### ISSUE TITLE
multi strings don't work in door setup module

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#26]
**Describe the bug**
when you add a multi-string to pass it sets the input to 0
**To Reproduce**
1. try to add a multi-string pass
**Expected behavior**
adding your input

**Screenshots**
![2023-01-19_17 37 11](https://user-images.githubusercontent.com/123119027/213577911-bcc7abcd-c57e-49b4-9292-4ad78defc18f.png)
then: (always the same for me)
![2023-01-19_17 37 18](https://user-images.githubusercontent.com/123119027/213577922-e0abf443-7bd9-4466-9a0f-1b9cbc8540b7.png)
then:
![2023-01-19_17 37 22](https://user-images.githubusercontent.com/123119027/213577936-b7aa5308-27c4-45e5-88d0-ea4ea28d43d6.png)

**Mod versions:**
 -Open Computers version: OpenComputers-MC1.12.2-1.7.7+5413028.jar
 -Open Security version: OpenSecurity-1.12.2-1.0-93.jar

**Comment by enderman-2009** [comment]
it also seems consistent

**Comment by cadergator10** [comment]
It's always the little things you forget that create major problems. It's all fixed now, thank you.

Just reinstall all the modules again now... yeeah lol. Hopefully when I learn networking updating modules will be a lot simpler as well as creating modules
