### ISSUE TITLE
diagnostic tablet : diagnostic/main door info/pass rules/entire door info not working

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#29]
# diagnostic tablet : diagnostics not working
**Describe the bug**
1. the diagnostics are broken

**To Reproduce**
Steps to reproduce the behavior (2 ways do the same for me) :

1. run diagnostic
2. press 1 for diagnostics
3. press 1/2/3
4. use the _ADMIN DIAGNOSTIC CARD_ on a reader
or
1. run diagnostic
2. press 1 for diagnostics
3. use the _ADMIN DIAGNOSTIC CARD_ on a reader

**Expected behavior**
giving the info

**Screenshots**
![2023-01-20_13 26 58](https://user-images.githubusercontent.com/123119027/213779129-92a9fa24-fa5b-4cd4-8981-989cf94851fb.png)

**Mod versions:**
 -Open Computers version: OpenComputers-MC1.12.2-1.7.7+5413028.jar
 -Open Security version: OpenSecurity-1.12.2-1.0-93.jar

**Additional context**
i have : 
1. door program (made from database) with : 
  12 doors
  12 sectors
  12 readers
2. server version : servertine 3.0.1
3. security database | v3.0.1
4. diagnostic last github version i just downloaded
  port = 5762
  cryptKey = {3, 5, 4, 1, 2}

**Comment by enderman-2009** [comment]
actualy not just pass rules all 3 diagnosticks options

**Comment by enderman-2009** [comment]
all 3 do the same btw

**Comment by cadergator10** [comment]
![smg4-mario](https://user-images.githubusercontent.com/75097681/213801111-7c6dba97-deac-4f24-af68-d7127c11e584.gif)
Here comes the beeg sad ;-;

Ok, ima take a look at it.

**Comment by cadergator10** [comment]
At least it doesn't just break now and tells you the exception

**Comment by cadergator10** [comment]
Diagnostics are currently working on my end. I'll have to replicate something similar to yours later (12 sectors and 12 doors)
I'll do this later today, cause atm, I gotta go

**Comment by enderman-2009** [comment]
i included cause it wasn't precise and it seemed like it could be because of that

**Comment by cadergator10** [comment]
Diagnostics has been fixed. It was it detecting the diagnostic program being killed off on the first scan, but its fixed now

Also you should reinstall all the modules, because there was an error in the Sector server module
