### ISSUE TITLE
lockdown light not being lit when supposed to

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#30]
**Describe the bug**
the lockdown light sometimes stays down even when the lockdown is active

**To Reproduce**
1. use a bypass type open door card on a lockdown door

**Expected behavior**
being lit

**Comment by cadergator10** [comment]
I replicated the error and I'll try to fix it sometime tomorrow

**Comment by cadergator10** [comment]
I think it should be solved. I'll close it if the bug is fixed. Just updating the doorcontrols with the autoinstaller should do the trick

**Comment by cadergator10** [comment]
I forgot an EEEEEND but it is fixed now and works, yey
