### ISSUE TITLE
Sector Control Suggestion

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#31]
# __SUGGESTIONS :__

1. adding an option for auto update (already added)
2. adding an option for open bypass lockdown

**Comment by cadergator10** [comment]
1. Wdym auto update? Like when I come out with a new sector control thing that you can easilly update it like with the autoinstaller and door controller? I mean it's possible, but I don't think incredibly important to putting effort into. Unless you mean auto update as in when you change the status of the door, it will automatically send changes, which I could add in as a configuration option next update.
2. You'll have to specify more. I'm not sure what you mean.

**Comment by enderman-2009** [comment]
no like you don't have to pulse the update line

**Comment by enderman-2009** [comment]
like the open sector works when the lockdown is enabled

**Comment by cadergator10** [comment]
> like the open sector works when the lockdown is enabled

That already works. You can still open a door if on knockdown only if l
1. You have the bypass lockdown pass
2. You have the passes to open the door if it wasn't on lockdown

**Comment by enderman-2009** [comment]
no like in the sctor control program

**Comment by cadergator10** [comment]
> no like in the sctor control program

Are you talking about the ability to either lock down the door or lock it open? That was intentional. Lockdown always takes priority of lock open. It doesn't make sense to lock a door shut as well as open. It's impossible

You would have to disable redstone going into the lockdown line then enable the redstone in the lock open line

**Comment by enderman-2009** [comment]
but you can activate both if you do open first

**Comment by enderman-2009** [comment]
also can you have 2 sector control?

**Comment by enderman-2009** [comment]
also it still closes if you try to open it when it is open by the sector control program

**Comment by cadergator10** [comment]
> also it still closes if you try to open it when it is open by the sector control program

I might take a look at this in the future, because it shouldn't let you use the door if locked open

**Comment by enderman-2009** [comment]
and it also stays open if you activate open then update then activate lockdown then update
