### ISSUE TITLE
bruh mineos sucks

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#32]
it softlocked cause not enough memory event tho i have max memory
with nothing opened btw

**Comment by enderman-2009** [comment]
4 t 3.5 is not enough WHAT

**Comment by enderman-2009** [comment]
also the editor kinda sucks it doesn't even work half of the time btw

**Comment by enderman-2009** [comment]
WTF :
![2023-01-23_14 01 28](https://user-images.githubusercontent.com/123119027/214126721-ce365c7e-52c4-468c-87fa-d80b9c6975c8.png)
its also 100% constent 100% usage idk how it doesn't crash

**Comment by enderman-2009** [comment]
it crashes in programs btw

**Comment by enderman-2009** [comment]
how did that even append

**Comment by cadergator10** [comment]
No idea. It's never happened to me though. I just have to restart the MineOS computer every once in a while. Also have to restart the computer mineos runs on every time I reload chunk or rejoin world. Its finicky and I've thought about moving it off mineos. I might when I have time to devote to it
