### ISSUE TITLE
i made a custom style :)

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#34]
i spent a pretty long time on this
![2023-01-23_16 12 06](https://user-images.githubusercontent.com/123119027/214151251-60e6e79a-41b2-4e43-9ca6-3086f22da14b.png)
![2023-01-23_16 11 29](https://user-images.githubusercontent.com/123119027/214151266-a15015fd-40db-4863-8997-b31a74f38b09.png)
![2023-01-23_16 11 15](https://user-images.githubusercontent.com/123119027/214151279-1b8d2d76-b73b-4e09-82ac-d27943a07cfe.png)
![2023-01-23_16 16 03](https://user-images.githubusercontent.com/123119027/214151704-dce73ebf-9f92-4135-a477-ebb7d4c8a128.png)

**Comment by cadergator10** [comment]
That's pretty nice looking. That'd be a pretty cool thing now that I think of it to add in the future: styles you can download

**Comment by enderman-2009** [comment]
can i send you it?

**Comment by enderman-2009** [comment]
@cadergator10 can i send you the file?

**Comment by enderman-2009** [comment]
this is the file :
{
  windowFill = 0x7a7a7a,

  listPanel = 0x444444,
  listBackground = 0x777777,
  listText = 0x5b5b5b,
  listAltBack = 0x666666,
  listAltText = 0x4b4b4b,
  listSelectedBack = 0x2b54a6,
  listSelectedText = 0xff9944,

  listPageButton = 0x555555,
  listPageText = 0xaaaaaa,
  listPageSelectButton = 0x880000,
  listPageSelectText = 0x6092f6,
  listPageLabel = 0x6092f6,

  passNameLabel = 0x6092f6,
  passIntLabel = 0x6092f6,
  passButton = 0x555555,
  passText = 0xaaaaaa,
  passSelectButton = 0x880000,
  passSelectText = 0x6092f6,
  passInputBack = 0x888888,
  passInputText = 0xbbbbbb,
  passInputPlaceholder = 0xaaaaaa,
  passInputFocusBack = 0xaaaaaa,
  passInputFocusText = 0xcccccc,

  bottomDivider = 0x444444,
  bottomButton = 0x555555,
  bottomText = 0xaaaaaa,
  bottomSelectButton = 0x880000,
  bottomSelectText = 0x6092f6,

  cardStatusLabel = 0x6092f6,
  cardStatusPanel = 0x555555,

  containerLabel = 0x6092f6,
  containerButton = 0x555555,
  containerText = 0xaaaaaa,
  containerSelectButton = 0x880000,
  containerSelectText = 0x6092f6,
  containerInputBack = 0x888888,
  containerInputText = 0xaaaaaa,
  containerInputPlaceholder = 0xbbbbbb,
  containerInputFocusBack = 0xaaaaaa,
  containerInputFocusText = 0xcccccc,
  containerComboBack = 0x555555,
  containerComboText = 0xaaaaaa,
  containerComboArrowBack = 0x666666,
  containerComboArrowText = 0xbbbbbb,

  sectorText = 0xaaaaaa,
  sectorButton = 0x555555,
  sectorSelectButton = 0x880000,
  sectorSelectText = 0x6092f6,
  sectorInputBack = 0x888888,
  sectorInputText = 0xaaaaaa,
  sectorInputPlaceholder = 0xbbbbbb,
  sectorInputFocusText = 0xaaaaaa,
  sectorInputFocusText = 0xcccccc,
  sectorComboBack = 0x555555,
  sectorComboText = 0xaaaaaa,
  sectorComboArrowBack = 0x666666,
  sectorComboArrowText = 0xbbbbbb,
}

**Comment by enderman-2009** [comment]
maybe you could add a color editor
