### ISSUE TITLE
security api setup function doesn't work with multi-strings

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#39]
if i try to check for a multi string this happens no matter my setup:
![2023-02-07_15 46 26](https://user-images.githubusercontent.com/123119027/217361825-1a32c961-6aab-415f-ab78-f7d525ec80cc.png)
idk what is going on but its clearly not normal and it literaly always happens in advanced mode for me

**Comment by cadergator10** [comment]
That looks about right.

If your talking about it asking for multiple strings to add to one add pass, that's not how it works. Multistrings are the same as normal strings but one user card can have multiple different strings in one pass (basically a much more configurable group pass)

**Comment by enderman-2009** [comment]
no the thing is it say error in cardRead area for num 2

**Comment by enderman-2009** [comment]
@cadergator10 and it doesn't let me configure it unlike regular string

**Comment by cadergator10** [comment]
Ah I see
It might be a similar issue that I had with the other error earlier. Ill quickily look

Also will transfer to the opensecurity repo since this is the modified version of serpapi

**Comment by cadergator10** [comment]
Bug fixed and done. Same issue as before just like I thought.
