### ISSUE TITLE
whatever this is

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#40]
**Describe the bug**
the door seams to appear twice but only the second one works somehow

**To Reproduce**
idk what the issue is but i can give my setup
**Expected behavior**
only appearing once

**Screenshots**
![2023-02-23_19 06 15](https://user-images.githubusercontent.com/123119027/221059878-c31ac6ed-b53f-4143-8fdd-ef41924f74bf.png)
![2023-02-23_19 07 43](https://user-images.githubusercontent.com/123119027/221059892-8e9f2760-bc27-4a25-82b6-8a39d6e6b0a6.png)

**Mod versions:**
OpenComputers-MC1.12.2-1.7.7+5413028.jar
OpenSecurity-1.12.2-1.0-93.jar

**Other Mods (optional in case it's being used as part of a system**
Computronics-1.12.2-1.6.6.jar, for creative memory(very high memory)

**MY SETUP:**
server:
![2023-02-23_19 11 22](https://user-images.githubusercontent.com/123119027/221060081-6c3a9233-1a98-476f-b2d0-79d391308061.png)
rangeExtander:
![2023-02-23_19 12 04](https://user-images.githubusercontent.com/123119027/221060168-a3acd532-d165-4f01-8d4c-979b3f1c7d5c.png)
diagnostic table:
![2023-02-23_19 12 36](https://user-images.githubusercontent.com/123119027/221060249-0878a305-e152-4850-b9bd-4c30552a7059.png)
door computer:
![2023-02-23_19 13 09](https://user-images.githubusercontent.com/123119027/221060314-2717ae1b-70ca-47f8-ae58-fa74c5c24afb.png)

**Comment by enderman-2009** [comment]
wait its probably just stupid networking again

**Comment by enderman-2009** [comment]
yeah it was just my worst ennemy networking

**Comment by cadergator10** [comment]
Quick note: i think you only need one creative memory module.
