### ISSUE TITLE
i want to help test stuff out

### ISSUE THREAD

**Issue by enderman-2009** [cadergator10/opencomputer-security-system#41]
how can i test modules changes and other stuff?
like how do i get the modules from other locations?

**Comment by cadergator10** [comment]
New Servertine version should allow testing of development branch modules way easier than what I had to do before (download files individually lol). I'll also now know where to look if I want someone else to help test out the stuff.

**Comment by enderman-2009** [comment]
ok

**Comment by enderman-2009** [comment]
for weekdays i have around 5 hours per day of time i could potentially use for this and weekends i have around 6 hours

**Comment by enderman-2009** [comment]
i already found a few bugs

**Comment by enderman-2009** [comment]
also i don't ask for anything in return

**Comment by cadergator10** [comment]
Closing since this isn't an issue and just a question
